# Generated by Django 6.0.1 on 2026-03-07 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_favoritespot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='spot',
            old_name='address',
            new_name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spot_type',
        ),
    ]
